#!/usr/bin/env bash
# configures a server to listen on port 80 of all server's active IPv4 IPs
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default
sudo service nginx restart
